name: Auto-merge Dependabot PR
on: pull_request

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.5.0
        with:
          merge-method: rebase
